### ISSUE TITLE
Redismq Can't find queue

### ISSUE THREAD

**Issue by ylc88** [zhaohaoh/redis-mq#1]
@RedisListener添加了queue的名称
Message 也设置了setQueue 但是发送消息报错，是我的接入有问题吗

com.redismq.exception.RedisMqException: Redismq Can't find queue
	at com.redismq.core.RedisMQProducer.hasQueue(RedisMQProducer.java:472)
	at com.redismq.core.RedisMQProducer.sendMessage(RedisMQProducer.java:102)
	at com.redismq.utils.RedisMQTemplate.sendMessage(RedisMQTemplate.java:31)

**Comment by ylc88** [comment]
找到问题了，关闭
